title: Lena Hickson Long
tagline: Software engineer in California
description: Personal site and blog of Lena Hickson Long.
url: https://lena.dev
permalink: pretty

author:
  name: Lena Hickson Long
  email: web@lena.dev

github_username: love-lena

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
